### ISSUE TITLE
TCP & windows support

### ISSUE THREAD

**Issue by xeijin** [szermatt/emacsclient-commands#1]
hello, thank you for this helping alot with a cli app I am writing for some basic emacs control.

Are there any future plans to add TCP support at all? This would mean Windows could be used too making this a pretty powerful cross-platform library.

**Comment by szermatt** [comment]
Thank you for your feedback. The lack of TCP support was mostly due to a lack of interest. Since there is interest, I'll try and add that. 

Note that commands such as `erun` and `ebuf` are likely going to be slower on Windows, since they won't benefit from some speed optimisations that are unix-specific.
